# Generated by Django 5.1.5 on 2025-02-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szerzok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szerzo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Szerzok',
            },
        ),
        migrations.CreateModel(
            name='Konyvek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=100)),
                ('szerzok', models.ManyToManyField(related_name='konyvek', to='alkalmazas.szerzok')),
            ],
            options={
                'verbose_name_plural': 'Konyvek',
            },
        ),
    ]
