# Generated by Django 5.1.5 on 2025-02-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alkalmazas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mufajok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mufaj', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Mufajok',
            },
        ),
        migrations.AddField(
            model_name='konyvek',
            name='mufajok',
            field=models.ManyToManyField(related_name='konyvek', to='alkalmazas.mufajok'),
        ),
    ]
