# Generated by Django 5.1.5 on 2025-02-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alkalmazas', '0002_mufajok_konyvek_mufajok'),
    ]

    operations = [
        migrations.AddField(
            model_name='konyvek',
            name='kiadas_eve',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='konyvek',
            name='kiado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='konyvek',
            name='kotes_tipus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='konyvek',
            name='leiras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='konyvek',
            name='nyelv',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='konyvek',
            name='oldalszam',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
